### ISSUE TITLE
Update Make metrics-status

### ISSUE THREAD

**Issue by sgoggins** [OSSHealth/augur#113]
1. Include front end/backend checkboxes
2. Include endpoint URL for backend's that are implemented
3. Ensure that all endpoints in Server.py are alphabetized according to CHAOSS category of metric
4. All metrics not referenced in the CHAOSS working group are under "Experimental" Headings as defined by @ccarterlandis 💯  Prototype. 
5. Rename source file functions and front end sources to be the names of the metrics they are defining. The metrics endpoints will remain the same in order to not abandon any current API users.

**Comment by ccarterlandis** [comment]
Items 3, 4, and 5 have been completed. After updating the API docs in `server.py` and making sure everything is clean, I shift my focus to updating `make metrics-status`.

**Comment by ccarterlandis** [comment]
Completed updating `make metricsstatus` with [this](https://github.com/OSSHealth/augur/co-mmit/796aea797c98d0f319662913dd26bcc4ef50cc10) commit.
