### ISSUE TITLE
Conda: command not found during installation

### ISSUE THREAD

**Issue by Nebrethar** [OSSHealth/augur#129]
The Augur installer is not able to find my installation of Conda on its own.
I am using Ubuntu 16.04 and have completed all installation steps prior. I will run either one of these commands:

```
make install-dev
make install-dev-admin
```

I receive these error messages after the initial line and the installation continues:
```
bash: activate: No such file or directory
bash: conda: command not found
```
I was able to circumvent it with this command for now, and it has to be used to run conda at all:

`export PATH=~/anaconda3/bin:$PATH`

It leads to an incomplete installation for me.
Attached is a picture of my issue.

![image](https://user-images.githubusercontent.com/34951354/41619923-ac73ed9e-73cd-11e8-94c6-3b7cfbd1765f.png)
![image](https://user-images.githubusercontent.com/34951354/41620076-37530198-73ce-11e8-8700-bd7587d2730b.png)

**Comment by sgoggins** [comment]
Make sure that "conda" is a command that is in your path.  Sometimes with tools like zsh or other developer shells, the path is not carried over from your .bash_profile.  If you issue the command "which conda" and it doesn't find conda, that means its not in your path.  Usually adding it to your path is a simple matter of exporting the environment variable "PATH" to include conda's path.
