### ISSUE TITLE
Add indicators for loading and lack of data to charts

### ISSUE THREAD

**Issue by ccarterlandis** [OSSHealth/augur#135]
While a chart is loading, there should be some sort of indicator, so that it does not look like the chart is broken. Similarly, if there is no data for a given chart, a message should also be displayed so that the user does not the think the endpoint is broken.

**Comment by sgoggins** [comment]
Yes. Yes. 1,000 times, yes, @ccarterlandis 🥇

**Comment by gabe-heim** [comment]
Added loading animation and error symbol after a 10 second timeout of no data being loaded.
