### ISSUE TITLE
Line chart "days average" not working in dev

### ISSUE THREAD

**Issue by sgoggins** [OSSHealth/augur#138]
The default is empty. If I enter a value it does not see to have an effect.

**Comment by sgoggins** [comment]
I take it back on the entry of a value.  It does have an effect if I hit enter. 

But the default, which I suspect remains at 180, is still "empty" to the user's view.

**Comment by gabe-heim** [comment]
Fixed by using the "value" attribute rather than having a placeholder. Will be pushed to dev soon.
