### ISSUE TITLE
Odd behavior on deployed twitter version

### ISSUE THREAD

**Issue by sgoggins** [OSSHealth/augur#140]
The first repo is not returning any data
Link on the facade page: 
http://opendata.missouri.edu/repositories?repo=1

Link on our Augur instance: 
http://twitter.augurlabs.io/?git=Z2l0aHViLmNvbS90d2l0dGVyL3R3ZW1vamk=&repo=twitter+twemoji

No clear reason why the first repo would be turning in nothing other than the likelihood we're not handling a boundary condition for the first row somewhere :)

**Comment by ccarterlandis** [comment]
<img width="991" alt="screen shot 2018-08-12 at 7 36 00 pm" src="https://user-images.githubusercontent.com/31522931/44008261-03f1a840-9e67-11e8-882d-210998517336.png">
For me, twitter/twemoji is returning data. Is this the repo you were meaning?

**Comment by ccarterlandis** [comment]
Bump ^ @sgoggins

**Comment by sgoggins** [comment]
This was fixed by Derek. 

Sean P. Goggins
(816) 368-1364
http://www.seangoggins.net
visit: http://www.sociotech.net
visit: http://www.datafactories.org 

"I force people to have coffee with me, just because I don't trust that a friendship can be maintained without any other senses besides a computer or cellphone screen.”
— John Cusack


On Aug 24, 2018, at 22:02, Carter Landis <notifications@github.com> wrote:

Bump ^ @sgoggins

**Comment by ccarterlandis** [comment]
Gotcha. Closed
