### ISSUE TITLE
Compress space used by Metrics-Status

### ISSUE THREAD

**Issue by sgoggins** [OSSHealth/augur#142]
I think the metrics status is taking up too much space on the page.  We should show people more information for the screen real estate we are taking up. IMHO. Subject to discussion.

**Comment by ccarterlandis** [comment]
I've been toying with the idea of making the metrics-status page have tabs in the same way that the metrics do already. Or, having them be drop-down menus, or possibly have the results be filterable by varying fields. Either way, I definitely want to change the format - I'll get started on this as soon as I finish refactoring the endpoint.
