### ISSUE TITLE
requirements.txt updates / 2 locations

### ISSUE THREAD

**Issue by sgoggins** [OSSHealth/augur#144]
I just want to check on the configuration here. There's a requirements.txt that's in the project root and another in the augur/ subdirectory under root.

The one in the augur/ subdirectory is in the .gitignore file.

When I did 
```
make docs
```

I got an error indicating the coloredlogs was not installed in my environment. 

I updated requirements.txt at the root (not in the augur/ subdirectory), rebuilt everything. Then 
```
make docs
```
worked. 

What are these different versions/locations for the requirements.txt for?

**Comment by howderek** [comment]
There should not be a requirements.txt in augur/

**Comment by sgoggins** [comment]
This seems to be related to me doing something stupid. Not sure how it got there, but its **gone**!
