### ISSUE TITLE
Some APIs return 404 on twitter deployed version

### ISSUE THREAD

**Issue by OrkoHunter** [OSSHealth/augur#148]
Status
- [x] `/:owner/:repo/timeseries/issue_comments`
- [x] `/:owner/:repo/watchers` (Note: Has been moved to `/:owner/:repo/timeseries/watchers`)
- [ ] `/:owner/:repo/timeseries/community_age`
- [x] `/:owner/:repo/timeseries/contributions`
- [x] `/:owner/:repo/timeseries/project_age`
- [x] `/:owner/:repo/timeseries/pulls/acceptance_rate` (Has been deprecated)
---

The API `/:owner/:repo/timeseries/issue_comments` returns a 404 for the twitter deployed version. Examples - 

http://twitter.augurlabs.io/api/unstable/twitter/twemoji/timeseries/issue_comments
http://twitter.augurlabs.io/api/unstable/twitter/finatra/timeseries/issue_comments

**Comment by OrkoHunter** [comment]
Same issues with `:/:owner/:repo/watchers`

Both are the only two APIs under [`Activity` section](https://osshealth.github.io/augur/api/index.html#api-Experimental-TotalContributions)

**Comment by OrkoHunter** [comment]
Same issue with `:owner/:repo/timeseries/community_age`

Example: http://twitter.augurlabs.io/api/unstable/twitter/finatra/timeseries/community_age
http://twitter.augurlabs.io/api/unstable/twitter/twemoji/timeseries/community_age

**Comment by OrkoHunter** [comment]
Same issue with `/:owner/:repo/timeseries/contributions`

Examples -
http://twitter.augurlabs.io/api/unstable/twitter/finagle/timeseries/contributions
http://twitter.augurlabs.io/api/unstable/twitter/twemoji/timeseries/contributions

**Comment by OrkoHunter** [comment]
Same issue with `/:owner/:repo/timeseries/project_age`

Examples -
http://twitter.augurlabs.io/api/unstable/twitter/twemoji/timeseries/project_age
http://twitter.augurlabs.io/api/unstable/twitter/finagle/timeseries/project_age

**Comment by OrkoHunter** [comment]
Same issue with `/:owner/:repo/timeseries/pulls/acceptance_rate`

Examples-
http://twitter.augurlabs.io/api/unstable/twitter/finagle/timeseries/pulls/acceptance_rate
http://twitter.augurlabs.io/api/unstable/rails/rails/timeseries/pulls/acceptance_rate

**Comment by ccarterlandis** [comment]
Hi @OrkoHunter,

Looking at our latest dev build, most of these metrics have been converted into a timeseries if they weren't already, and if they were a timeseries metric they have been converted into a non-timeseries metric (if that makes sense). My guess is that most of these did not get updated or tested correctly before they got deployed since we don't have frontend visualizations for most of these metrics.

As a result, I figured that `/:owner/:repo/watchers` should actually be `/:owner/:repo/timeseries/watchers`. The others, I'm not sure about, but I will look into them tonight for you! Sorry about all these broken endpoints!

**Comment by OrkoHunter** [comment]
Bringing the `watchers` metric to timeseries is a fantastic feature. Thanks for that! (Marking it solved)

There is absolutely no need to be sorry, thank you all for working on this wonderful project. :)

**Comment by OrkoHunter** [comment]
That's for the update on this @howderek!

**Comment by ccarterlandis** [comment]
Documentation should be up to date on this now - if there are still any broken endpoints, feel free to reopen.
