### ISSUE TITLE
Question about /git/lines_changed/:git_repo_url

### ISSUE THREAD

**Issue by OrkoHunter** [OSSHealth/augur#150]
Hi!

I am trying to use the API `/git/lines_changed/:git_repo_url` but I am not sure how to send the correct `git_repo_url`

URLs I tried with no help
http://twitter.augurlabs.io/api/unstable/git/lines_changed/github.com/rails/rails/
http://twitter.augurlabs.io/api/unstable/git/lines_changed/github.com/rails/rails.git/
http://twitter.augurlabs.io/api/unstable/git/lines_changed/https://github.com/rails/rails/
http://twitter.augurlabs.io/api/unstable/git/lines_changed/https://github.com/rails/rails.git/
http://twitter.augurlabs.io/api/unstable/git/lines_changed/rails/rails
http://twitter.augurlabs.io/api/unstable/git/lines_changed/rails/rails.git

I'm sorry for asking so many things on the same day, please respond when there is time. :)

**Comment by howderek** [comment]
Are you using the dev branch or master branch?

**Comment by sgoggins** [comment]
@OrkoHunter : Note that the git lines are only going to work for the repos that are downloaded on your site.  The source is an actual clone of the git repo. 
@howderek and @ccarterlandis : I am looking at the dev branch right now and the API routes do not seem to be up.  Also notable: The list of GitHub repositories on the homepage is now gone.

**Comment by sgoggins** [comment]
@OrkoHunter ... i.e., "rails/rails" won't work unless we clone that repository ...

**Comment by OrkoHunter** [comment]
Oh, that makes good sense. Thanks @sgoggins!

**Comment by ccarterlandis** [comment]
@howderek IIRC, this endpoint was removed, right? Is it coming back?

**Comment by ccarterlandis** [comment]
@howderek I am still having trouble with this. I'm using `/git/changes_by_author/github.com/twitter/twemoji` (which I thought had worked before) but to no avail.

**Comment by ccarterlandis** [comment]
Due to the fact that browsers don't like when you put a URL inside a URL (for obvious reasons), this endpoint will no longer be able to be used like `git/changes_by_author/github.com/twitter/twemoji/`. Instead, use the base64 encoding of the URL and pass it as the `repo_base_url` query parameter, like so: `git/changes_by_author/?repo_url_base=Z2l0aHViLmNvbS90d2l0dGVyL3R3ZW1vamk=` (which is `twitter/twemoji`).
