### ISSUE TITLE
New endpoints for watchers

### ISSUE THREAD

**Issue by OrkoHunter** [OSSHealth/augur#153]
Currently, there is an endpoint `/:owner/:repo/timeseries/watchers` which returns a timeseries of the change in the number of watchers for a project.
It would be beneficial to have another endpoint which gives a timeseries of the gross number of watchers.

**Comment by ccarterlandis** [comment]
Added in commit [05b3f5f](https://github.com/OSSHealth/augur/commit/05b3f5fde22c0bab356b8536a814ab8d6d9e2410).
