### ISSUE TITLE
Missing Data in Graphs on Comparison Charts

### ISSUE THREAD

**Issue by sgoggins** [OSSHealth/augur#157]
Something is not updated in the comparisons from our latest API endpoint updates.  Look at this: 

![augur](https://user-images.githubusercontent.com/379847/44278412-82f56a00-a213-11e8-9fad-64464af784c7.png)

**Comment by ccarterlandis** [comment]
Fixed in [this](https://github.com/OSSHealth/augur/commit/efe6df9ee59bf1e3ceafb3f2901d01865504a6c1) commit.
