### ISSUE TITLE
Compared repos with no data should fail gracefully

### ISSUE THREAD

**Issue by ccarterlandis** [OSSHealth/augur#160]
Instead of displaying both the error chart and a data chart, if one of the compared repos in the compared card doesn't have any data, it should show a small error message that doesn't mess up the formatting and alignment of the other charts.

**Comment by gabe-heim** [comment]
Solved by bringing back legend and the message is shown on a gray legend label. Also, the "data is missing or unavailable" message/icon only shows if both batch requests fail.
