### ISSUE TITLE
Add batch requests

### ISSUE THREAD

**Issue by howderek** [OSSHealth/augur#59]
Adding batch requests to our API will improve the efficiency of communication between our frontend and backend greatly.

This API should also support different resolutions like weekly, monthly, etc. to further reduce the work required on the frontend to render the data. This could potentially reduce code duplication between projects that use our API and definitely improve performance on slow connections.

**Comment by sgoggins** [comment]
The back end of this is finished.  The front end adaptation is something we are negotiating. Sean is pushing Derek to lower complexity solutions.
