### ISSUE TITLE
Windows Docker Install Error Message

### ISSUE THREAD

**Issue by b-hodges** [OSSHealth/augur#72]
When installing on Windows 10 with docker (as described in the README) I skipped step 2 (adding environment variables) before running `docker-compose build`. It gave me this error message:

```
Building ghdata
ERROR: Windows named pipe error: The system cannot find the file specified. (code: 2)
```

This may be due to not having the database credentials, in which case a more explicit error message would be desirable, but if it is not then it is likely an error in the build process itself.

**Comment by sgoggins** [comment]
@b-hodges : is this issue also resolved with the pull request merge, or do issues persist? 
@howderek : thoughts.
