### ISSUE TITLE
Docker-compose issue

### ISSUE THREAD

**Issue by germonprez** [OSSHealth/augur#77]
@howderek -- A docker-compose question: 

docker-compose.yml is as such: 

``` version: '3'
 services:

   ghdata:
     build: .
     image: osshealth/ghdata
     restart: always
     volumes:
       - .:/ghdata
     ports:
       - "80:80"
     environment:
       GHDATA_DB_USER:XXX
       GHDATA_DB_PASS:XXX
       GHDATA_DB_PORT:3306
       GHDATA_DB_HOST:XXX.sociallycompute.XXX
       GHDATA_DB_NAME:ghtorrent
#       GHDATA_GITHUB_API_KEY:
#       GHDATA_PUBLIC_WWW_API_KEY:
```
Running against this gives: 

ERROR: The Compose file './docker-compose.yml' is invalid because:
services.ghdata.environment contains an invalid type, it should be an object, or an array

Should I be putting things in []?

**Comment by howderek** [comment]
Those values should be left blank and be set using environment variables on the host system. Blank values mean use whatever is on the host system. More information about docker-compose's environement configuration can be found here:

https://docs.docker.com/compose/compose-file/#environment

I recommend not setting these variable in the docker-compose.yml directly but instead setting them at runtime or by sourcing a script that sets the variables (such as your `~/.profile`). Please note that docker-compose.yml is tracked by the repo so should you like to contribute changes, your changes in that file will be tracked.

**Comment by sgoggins** [comment]
@germonprez : We could distribute the read only database information that I shared with you for your students to a small group of people for whom we are deploying the docker image.

**Comment by sgoggins** [comment]
@howderek and @germonprez : Please let me know if you consider this issue resolved or if Docker issues are persisting.

**Comment by germonprez** [comment]
I'm fine for now -- in an effort to close this issue.

**Comment by sgoggins** [comment]
@germonprez : If you are not able to easily install and run our Docker image, especially compared to other CHAOSS software, I would like to leave it open. If you do not have time to "try again" right now, I will leave it open until we are more "validated" in our Docker image install.

**Comment by germonprez** [comment]
That's fine with me. Perhaps I'll have time in CA to do an install :)
