### ISSUE TITLE
Google Summer of Code Ideas

### ISSUE THREAD

**Issue by sgoggins** [OSSHealth/augur#82]
[ This issue for addressing questions and comments related to this GSoC idea, which is one of the ideas proposed by the [CHAOSS group for the 2018 edition of GSoC](https://wiki.linuxfoundation.org/chaoss/gsoc-ideas) ]

Currently, GHData includes a backend, written in Python, and a Front End, written in javascript using the Mozilla metrics.js library and other D3 based tools for visualization.  The purpose of the system is to test out new metrics and new metrics visualizations for the CHAOSS project.  

Examples and descriptions of the visualizations can be found here: https://goo.gl/2DPuc2

The aims of the project are as follows:

GHData is an open source software project that is developing as part of the CHAOSS project through our work in 2017. It fills an important technology niche not addressed by other analytics tools within the CHAOSS project. GHData is focused on building human-centered open source software health metrics, defined by collaborations of the CHAOSS project and other open source stakeholders. GHData is software focused on making sense of data using four key human-centered data science strategies:
1.	Enable comparisons. People navigate complex unknowns analogically. Let folks see how their project compares with others they are familiar with.
2.	Make time a fundamental dimension in all metrics. Point in time scores are useful. They are more useful if we can see how they compare historically and can be used to anticipate a trajectory.
3.	The provenance from raw data to metrics visualization is transparent.
4.	Enable downloadable visualizations as a .csv, .svg, or other data exchange format. This is because (a) people trust metrics when they can see the underlying data and (b) proving traceability back to the CHAOSS project's metrics standards requires easy transparency.

Writing Python code to query the GHTorrent databases (request credentials privately, through the mailing list) and obtain from it the metrics relevant for the report. Possible technologies to achieve this aim include Python Pandas and javascript. 

We are currently focused on building out new metrics and new forms of metrics visualizations.  [An alpha copy of the deployed software can be found here](http://ghdata.sociallycompute.io)

__Difficulty__: easy/medium
__Requirements__: Python programming. Interest in software analytics. Willingness to understand GHData internals. Interest in javascript and SQL are also valuable. 

__Recommended__: Experience with Python interfaces to databases would be convenient, but can be learned during the project. Experience with Latex and/or Python Jupyter Notebooks would help.
Mentors: @sgoggins, @jgbarah , @germonprez , @jcabot

**Microtasks**
do

Once you're familiar with installing the docker image or downloading the development framework: 

Microtask 1: Produce a new visualization for any of the existing metrics you find implemented under the ghdata directory.  Sources for GHTorrent, the GitHub API and Libraries.io are implemented. 

Microtask 2: Produce a chart showing the distribution of time-to-close (using the corresponding field in the GHTorrent database) for issues already closed, and opened during the last six months.

Microtask 3: Produce a listing of repositories, as a table and as CSV file, with the number of commits authored, issues opened, and pull requests opened, during the last three months, ordered by the total number (commits plus issues plus pull requests).

Microtask 4: Perform any other analysis you may find interesting, based on GHData's Python collectors/API access programs. 

If you want, you can also:

Microtask 5: Produce a pull request for GHData and try to follow instructions until it gets accepted. Try do do something simple that you consider useful, not necessarily fix to the code: improvement of comments, documentation or testing will usually be easier to get accepted, and very useful for the project. Please, avoid just producing a random pull request just to have another microtask: the objective is not that you get one more microtask done, but that you understand how to interact with developers in the project contributing with something that could be useful).
Of course, there is no need to do all the microtasks, you only need to show that your skills are in good standing for working in this project.

Showing the work you did
If you want to show the work you did, open a GitHub repository, and upload to it:

A README.md file explaining what you did, and linking to the results (which will be in the same repository, see below). This will be the main file to show your skills and interest on the project, so try to make it organized and clear, in a way that we can easily understand what you did.

Screenshots of the dashboard(s) you produced, and configuration files you used for them (if any). Please remember removing passwords and/or auth tokens that could be in them, before uploading. In the REAME.md file, link all those files, telling about which GitHub projects you analyzed.

Python scripts you produced, with enough information (in comments and/or in the README.md file) so that we can run them if needed. Upload Python scripts ready to work assuming GHData is already installed. 

Links to the pull request you did (if any), along with any comment you may have about it.

[Contributing to GHData](https://github.com/OSSHealth/ghdata/tree/master/docs)

[CHAOSS Metrics (work in progress)](https://wiki.linuxfoundation.org/chaoss/metrics#chaoss-oss-project-metrics)

Asking for help
If you need help, please use the following channels.

For issues related to GrimoireLab:

[#chaoss-community channel in Freenode IRC](https://freenode.net/)

[CHAOSS mailing list](https://lists.linuxfoundation.org/mailman/listinfo/oss-health-metrics)

**Comment by sreetamparida** [comment]
I have completed one of those microtask and i want to work with you on this project for GSoC 2018. What am i supposed to do?

**Comment by GeorgLink** [comment]
Hi @sreetamparida,

This email outlines your next steps:
https://lists.linuxfoundation.org/pipermail/oss-health-metrics/2018-February/000517.html

>

**Comment by apoorvkhare07** [comment]
Hi @sgoggins @GeorgLink I am interested in this project for GSoC'18, I am already halfway down with microtasks completion. 
I wanted to know whether there is some specific template for the proposal ? or something specific you demand in the proposal ?
Also wanted to know where I can study more about Ghdata and the project's exact aims and demand ?

Thankyou

**Comment by GeorgLink** [comment]
For proposal guidelines, see our email archive:
https://lists.linuxfoundation.org/pipermail/oss-health-metrics/2018-March/000532.html

The most information about GHData is on the repository.

**Comment by darkLord19** [comment]
Sorry for the inconvenience but can you please explain microtask 1 in details? What are we supposed to do? Write a Python script or use ghdata dashboard to generate visualization?

**Comment by apoorvkhare07** [comment]
@sgoggins @GeorgLink I too have the same doubt as @darkLord19, in first task we have to create the visualisation using Ghdata daskboard or python script using Ghdata ?

**Comment by sgoggins** [comment]
We will accept visualizations either way. 

We understand that not everyone is going to be skilled in javascript AND python.  If you are familiar with one, more than the other, use the tools that work to your strengths. 

Sean
